[package]
name = "pydbtguard"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "pydbtguard"
crate-type = ["cdylib"]

[dependencies]
pydbtguard-core = { path = "../../crates/pydbtguard-core" }
pyo3 = { version = "0.21", features = ["extension-module"] }
serde_json = "1.0"
